# Generated by Django 5.2.2 on 2026-06-02 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('logo_url', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_codes', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('body_style', models.CharField(blank=True, max_length=64)),
                ('production_start', models.DateField()),
                ('production_end', models.DateField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='catalog.carmodel')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='catalog.make')),
            ],
            options={
                'ordering': ['production_start'],
            },
        ),
        migrations.AddField(
            model_name='carmodel',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='catalog.make'),
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('variant_name', models.CharField(blank=True, max_length=128)),
                ('engine_code', models.CharField(blank=True, max_length=64)),
                ('engine_displacement_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('other', 'Other')], max_length=16)),
                ('transmission_type', models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cvt', 'CVT'), ('dct', 'DCT'), ('other', 'Other')], max_length=16)),
                ('transmission_detail', models.CharField(blank=True, max_length=128)),
                ('cab_type', models.CharField(blank=True, max_length=64)),
                ('drive_type', models.CharField(blank=True, choices=[('fwd', 'FWD'), ('rwd', 'RWD'), ('awd', 'AWD'), ('4wd', '4WD')], max_length=8)),
                ('power_hp', models.PositiveIntegerField(blank=True, null=True)),
                ('production_start', models.DateField()),
                ('production_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='catalog.generation')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('make', 'slug')},
        ),
    ]
