# Generated by Django 5.2.14 on 2026-06-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='chassis_codes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
