# Generated by Django 5.0.8 on 2026-06-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_generation_chassis_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='make_logos/'),
        ),
    ]
