# Generated by Django 5.2.13 on 2026-04-13 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0005_phase4_listing_pricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('state', models.CharField(choices=[('payment_pending', 'Payment pending'), ('paid_escrow', 'Paid into escrow'), ('refund_pending', 'Refund pending'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('hold', 'On hold'), ('available_for_payout', 'Available for payout')], default='payment_pending', max_length=32)),
                ('fitment_verified_at', models.DateTimeField()),
                ('return_policy_ack_at', models.DateTimeField()),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=128)),
                ('stripe_client_secret', models.CharField(blank=True, max_length=255)),
                ('payout_blocked', models.BooleanField(default=False)),
                ('payout_block_reason', models.CharField(blank=True, max_length=255)),
                ('payout_block_deadline', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refund_requested_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('hold_until', models.DateTimeField(blank=True, null=True)),
                ('released_to_seller_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_bought', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_sold', to=settings.AUTH_USER_MODEL)),
                ('vehicle_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vehicles.vehiclepart')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SellerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account_id', models.CharField(blank=True, max_length=128)),
                ('connect_onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('id_verified_at', models.DateTimeField(blank=True, null=True)),
                ('ssn_verified_at', models.DateTimeField(blank=True, null=True)),
                ('first_sale_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
