# Generated by Django 5.2.14 on 2026-06-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_bundle_cartbundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='shipping_mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('economy', 'Economy')], default='standard', max_length=16),
        ),
    ]
