# Generated by Django 5.2.13 on 2026-04-13 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_auto_cancelled_for_no_confirm_at_and_more'),
        ('vehicles', '0005_phase4_listing_pricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='source_quote_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('vehicle_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='vehicles.vehiclepart')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'vehicle_part'), name='uniq_cart_item_user_vehicle_part')],
            },
        ),
    ]
