# Generated by Django 5.2.13 on 2026-04-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_pickup_selected_order_source_quote_id_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='next_day_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
