# Generated by Django 5.2.13 on 2026-04-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_buyer_state_order_buyer_zip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='buyer_zip_snapshot',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='shipping_mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('next_day', 'Next day'), ('pickup', 'Pickup')], default='standard', max_length=24),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='shipping_quoted_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Buyer-paid shipping line included in amount_usd.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_mode',
            field=models.CharField(blank=True, help_text='standard | next_day | pickup — chosen at checkout.', max_length=24),
        ),
    ]
