# Generated by Django 5.2.13 on 2026-04-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cartitem_buyer_zip_snapshot_cartitem_shipping_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='buyer_notes',
            field=models.TextField(blank=True, help_text='Buyer instructions (e.g. side, color code) shown to the seller with the order.'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_notes',
            field=models.TextField(blank=True, help_text='Buyer instructions from checkout (e.g. side, options).'),
        ),
    ]
