# Generated by Django 5.2.13 on 2026-04-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_payment_method_seller_verification_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_slot_end',
            field=models.TimeField(blank=True, help_text='Pickup window end (local time).', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_slot_start',
            field=models.TimeField(blank=True, help_text='Pickup window start (local time, same calendar day as pickup_window_start).', null=True),
        ),
    ]
