# Generated by Django 5.2.13 on 2026-04-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_pickup_slot_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='auto_cancelled_for_no_confirm_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='next_day_selected',
        ),
        migrations.RemoveField(
            model_name='order',
            name='overage_acknowledged_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_completed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_completion_photos',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_scheduled_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_selected',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_slot_end',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_slot_start',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_window_end',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_window_start',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller_label_debit_usd',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_request_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_instructions',
            field=models.TextField(blank=True, help_text='Instructions to the seller from admin (how to package/ship).'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_paid_at',
            field=models.DateTimeField(blank=True, help_text='When buyer paid for shipping separately.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='Carrier tracking URL for buyer.'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='buyer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='shipping_mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('next_day', 'Next day')], default='standard', max_length=24),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='order',
            name='funds_held_until_delivered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipping amount — charged separately after purchase.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_label_url',
            field=models.URLField(blank=True, help_text='Label PDF uploaded by admin.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_mode',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_from_checkout', to='orders.cartitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('payment_pending', 'Awaiting payment'), ('paid_escrow', 'Paid — awaiting shipment'), ('seller_confirmed', 'Seller confirmed'), ('label_processing', 'Shipping label processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('refund_pending', 'Refund pending'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('hold', 'On hold'), ('available_for_payout', 'Available for payout')], default='payment_pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
