# Generated by Django 5.2.13 on 2026-04-13 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('illustration_key', models.SlugField(help_text='Stable key for SVG/illustration lookup (e.g. engine, brakes).', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Part categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=96)),
                ('name', models.CharField(max_length=255)),
                ('buy_new_only', models.BooleanField(default=False, help_text='If true, never offered to sellers (belts, pads, etc.).')),
                ('variant_templates', models.JSONField(blank=True, default=list, help_text='List of dicts, e.g. [{"side": "left"}, {"side": "right"}] or [] for one row.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_families', to='vehicles.partcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_part_families', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Part families',
                'ordering': ['category__sort_order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('trim', models.CharField(blank=True, max_length=128)),
                ('engine', models.CharField(blank=True, max_length=255)),
                ('transmission', models.CharField(blank=True, max_length=128)),
                ('drivetrain', models.CharField(blank=True, max_length=64)),
                ('body_style', models.CharField(blank=True, max_length=64)),
                ('color', models.CharField(blank=True, max_length=64)),
                ('location_state', models.CharField(blank=True, max_length=2)),
                ('location_zip', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('analytics_status', models.CharField(default='pending', help_text='pending | ready | failed — Celery/eBay in Phase 3.', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('exterior', 'Exterior'), ('engine_bay', 'Engine bay'), ('interior', 'Interior'), ('odometer', 'Odometer')], max_length=32)),
                ('image', models.ImageField(upload_to='vehicle_photos/%Y/%m/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_key', models.CharField(blank=True, default='', max_length=256)),
                ('label', models.CharField(max_length=512)),
                ('listing_state', models.CharField(choices=[('draft', 'Draft (not priced)'), ('message_only', 'Message seller'), ('buy_now', 'Buy now'), ('sold', 'Sold'), ('unavailable', 'Unavailable'), ('sold_elsewhere', 'Sold elsewhere')], default='draft', max_length=32)),
                ('condition_draft', models.CharField(blank=True, choices=[('oem_untested', 'OEM — untested'), ('oem_tested', 'OEM — tested working'), ('aftermarket', 'Aftermarket'), ('new', 'New'), ('used', 'Used')], max_length=32, null=True)),
                ('color_override', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('size_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('size_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('size_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('size_packaged_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('size_packaged_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('size_packaged_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('use_vehicle_location', models.BooleanField(default=True)),
                ('location_note', models.CharField(blank=True, max_length=255)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('is_damaged', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False, help_text='Seller removed this line from their sellable catalog.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_parts', to='vehicles.partfamily')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['part_family__category__sort_order', 'part_family__name', 'variant_key'],
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'part_family', 'variant_key'), name='uniq_vehicle_part_family_variant')],
            },
        ),
    ]
