# Generated by Django 5.2.14 on 2026-06-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='seller_state',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
    ]
