# Generated by Django 5.2.13 on 2026-04-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_seed_part_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='analytics_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', help_text='processing while stub/Phase-3 job runs; ready when market step completes.', max_length=32),
        ),
    ]
