# Generated by Django 5.2.13 on 2026-04-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_analytics_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='analytics_last_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the last successful eBay market scrape finished.', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='analytics_next_refresh_at',
            field=models.DateTimeField(blank=True, help_text='Seller-triggered refresh allowed on or after this time (30-day rule).', null=True),
        ),
    ]
