# Generated by Django 5.2.13 on 2026-04-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_phase3_market_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepart',
            name='buy_now_expires_at',
            field=models.DateTimeField(blank=True, help_text='When set, Buy Now reverts to message-only after this time (Celery + API).', null=True),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD; required for Buy Now listings.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='return_policy',
            field=models.CharField(choices=[('red', 'Final sale — as-is (no returns)'), ('yellow', 'Partial returns — restocking fee may apply'), ('green', '30-day buyer protection (full refund)')], default='green', max_length=16),
        ),
    ]
