# Generated by Django 5.2.13 on 2026-04-27 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('vehicles', '0009_vehicle_pickup_and_return_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='mileage_unavailable',
            field=models.BooleanField(default=False, help_text="If true, mileage is unknown — buyers see 'Unavailable'."),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer_miles',
            field=models.PositiveIntegerField(blank=True, help_text='Odometer reading in miles.', null=True),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='offer_expires_at',
            field=models.DateTimeField(blank=True, help_text='When offer_price_usd stops applying.', null=True),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='offer_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Time-limited offer price (e.g. from seller quote); shown as Buy Now until expiry.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='offer_source_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_on_parts', to='messaging.quote'),
        ),
    ]
