# Generated by Django 5.2.13 on 2026-04-28 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehicle_mileage_unavailable_vehicle_odometer_miles_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=64)),
                ('option_label', models.CharField(max_length=128)),
                ('confidence', models.FloatField(default=1.0, help_text='AI confidence 0–1 that this option applies to the vehicle.')),
                ('needs_manual_check', models.BooleanField(default=False, help_text='True when confidence < 0.9 and seller must verify.')),
                ('is_applicable', models.BooleanField(default=True, help_text="False if AI determined the vehicle doesn't have this option.")),
                ('source', models.CharField(default='car_part_com', help_text='car_part_com | perplexity | manual | all', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ai_image_description',
            field=models.TextField(blank=True, help_text='Detailed AI-generated description of all visible parts and their condition.'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='exterior_color_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='interior_color',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='interior_color_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='paint_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='ai_description',
            field=models.TextField(blank=True, help_text='AI-generated condition description derived from vehicle images.'),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='grade',
            field=models.CharField(choices=[('A', 'Grade A — Excellent (< 60k miles or < 15k/yr)'), ('B', 'Grade B — Good (60k–200k miles, minimal repair)'), ('C', 'Grade C — Fair (> 200k miles or significant repair)'), ('X', 'Grade X — Ungraded / insufficient info')], default='X', help_text='A/B/C/X based on mileage and AI condition analysis.', max_length=2),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='listing_pipeline_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='listing_pipeline_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='listing_pipeline_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='listing_pipeline_status',
            field=models.CharField(default='idle', help_text='idle | processing | done | failed', max_length=32),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='local_pickup_only',
            field=models.BooleanField(default=False, help_text='If true, buyer cannot purchase — contact seller for local pickup only.'),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='package_size_category',
            field=models.CharField(blank=True, choices=[('small', 'Small (fits in box, ships parcel)'), ('medium', 'Medium (oversized box / freight)'), ('large', 'Large (pallet 48×48)'), ('pallet', 'Pallet'), ('crate', 'Crate')], help_text='AI-estimated packaging category; drives EasyShip vs FreightQuote routing.', max_length=16),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='primary_photo_section',
            field=models.CharField(blank=True, help_text='VehiclePhoto.Section key to use as the lead image in buyer-facing sliders.', max_length=32),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='shipping_disabled',
            field=models.BooleanField(default=False, help_text='Shipping not available; local pickup only (no buy button).'),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='size_packaged_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='size_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='vehiclephoto',
            name='section',
            field=models.CharField(choices=[('front_driver_corner', "Front-Driver's Corner (3/4 view)"), ('rear_passenger_corner', "Rear-Passenger's Corner (3/4 view)"), ('driver_side_profile', "Driver's Side Profile"), ('passenger_side_profile', "Passenger's Side Profile"), ('direct_front', 'Direct Front'), ('direct_rear', 'Direct Rear'), ('wheels', 'All Four Wheels/Tires'), ('damaged_areas', 'Damaged Areas'), ('front_cockpit', 'Front Cockpit (Dashboard)'), ('driver_seat', "Driver's Seat"), ('passenger_seat', 'Passenger Seat'), ('rear_seats', 'Rear Seats'), ('dashboard', 'Dashboard and Steering Wheel'), ('odometer', 'Odometer'), ('center_console', 'Center Console/Infotainment'), ('trunk', 'Trunk/Cargo Area'), ('engine_bay', 'Engine Bay'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='analytics_last_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='analytics_next_refresh_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='analytics_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condition_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='damage_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_damage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage_unavailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='odometer_miles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='return_policy_default',
            field=models.CharField(choices=[('red', 'Final sale — as-is (no returns)'), ('yellow', 'Partial returns — restocking fee may apply'), ('green', '30-day buyer protection (full refund)')], default='green', max_length=16),
        ),
        migrations.AlterField(
            model_name='vehiclepart',
            name='buy_now_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepart',
            name='condition_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehiclepart',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehiclepart',
            name='offer_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepart',
            name='offer_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclephoto',
            name='kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='BrowseErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(blank=True, max_length=512)),
                ('issue_description', models.TextField()),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='browse_error_reports', to=settings.AUTH_USER_MODEL)),
                ('vehicle_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_reports', to='vehicles.vehiclepart')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('year_range_start', models.PositiveSmallIntegerField()),
                ('year_range_end', models.PositiveSmallIntegerField()),
                ('trim', models.CharField(blank=True, max_length=128)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='vehicles.partoption')),
            ],
            options={
                'ordering': ['make', 'model', 'year_range_start'],
            },
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='selected_option',
            field=models.ForeignKey(blank=True, help_text='The specific part option (e.g. Left / LED) assigned to this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_parts', to='vehicles.partoption'),
        ),
        migrations.CreateModel(
            name='PartOptionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('found', 'Options found'), ('no_options', 'No options (All)'), ('year_range', 'Year range shown (car-part.com unknown)'), ('undefined', "car-part.com doesn't know this part"), ('failed', 'Scrape failed')], default='pending', max_length=16)),
                ('raw_options', models.JSONField(blank=True, default=list)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_sets', to='vehicles.partfamily')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_option_sets', to='vehicles.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'part_family')},
            },
        ),
        migrations.AddField(
            model_name='partoption',
            name='option_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='vehicles.partoptionset'),
        ),
        migrations.AlterUniqueTogether(
            name='partoption',
            unique_together={('option_set', 'option_key')},
        ),
    ]
