from django.urls import path

from .stripe_webhook import StripeWebhookView
from .views import (
    BuyerOrderInquiryView,
    CartCheckoutPreviewView,
    CartCheckoutView,
    CartItemDetailView,
    CartView,
    CashoutRequestView,
    CheckoutIntentView,
    ConfirmCashPaymentView,
    ConfirmOrderPaymentView,
    MoneySummaryView,
    OrderDetailView,
    OrderListView,
    OrderReceiptView,
    OrderStripeCheckoutSessionView,
    PurchaseListView,
    QuoteAcceptCheckoutView,
    SalesListView,
    SellerAnalyticsView,
    SellerActionQueueView,
    SellerConfirmOrderView,
    SellerPreShipChecklistView,
    SellerPurchaseLabelView,
    SellerReviewCreateView,
    SellerShippingPlanSuggestView,
    SellerShippingPlanView,
    SellerVerificationView,
    TrackingAdminOverrideView,
    TrackingWebhookView,
    VerifyCheckoutSessionView,
)

urlpatterns = [
    path("cart/", CartView.as_view(), name="cart"),
    path("cart/<int:item_id>/", CartItemDetailView.as_view(), name="cart-item-detail"),
    path("cart/preview-checkout/", CartCheckoutPreviewView.as_view(), name="cart-preview-checkout"),
    path("cart/checkout/", CartCheckoutView.as_view(), name="cart-checkout"),
    path("orders/payments/stripe/webhook/", StripeWebhookView.as_view(), name="stripe-webhook"),
    path("orders/checkout-session/verify/", VerifyCheckoutSessionView.as_view(), name="verify-checkout-session"),
    path("orders/purchases/", PurchaseListView.as_view(), name="order-purchases"),
    path("orders/sales/", SalesListView.as_view(), name="order-sales"),
    path("orders/checkout-intent/", CheckoutIntentView.as_view(), name="order-checkout-intent"),
    path("orders/quotes/<int:quote_id>/accept-checkout/", QuoteAcceptCheckoutView.as_view(), name="quote-accept-checkout"),
    path("orders/<int:order_id>/stripe-checkout/", OrderStripeCheckoutSessionView.as_view(), name="order-stripe-checkout"),
    path("orders/<int:order_id>/receipt/", OrderReceiptView.as_view(), name="order-receipt"),
    path("orders/<int:order_id>/buyer-inquiry/", BuyerOrderInquiryView.as_view(), name="order-buyer-inquiry"),
    path("orders/<int:order_id>/seller-review/", SellerReviewCreateView.as_view(), name="order-seller-review"),
    path("orders/<int:order_id>/confirm-payment/", ConfirmOrderPaymentView.as_view(), name="order-confirm-payment"),
    path("orders/<int:order_id>/confirm-cash-payment/", ConfirmCashPaymentView.as_view(), name="order-confirm-cash-payment"),
    path("orders/<int:order_id>/detail/", OrderDetailView.as_view(), name="order-detail"),
    path("orders/<int:order_id>/seller-confirm/", SellerConfirmOrderView.as_view(), name="order-seller-confirm"),
    path("orders/seller/action-queue/", SellerActionQueueView.as_view(), name="order-seller-action-queue"),
    path("orders/<int:order_id>/shipping-plan/suggest/", SellerShippingPlanSuggestView.as_view(), name="order-shipping-plan-suggest"),
    path("orders/<int:order_id>/shipping-plan/", SellerShippingPlanView.as_view(), name="order-shipping-plan"),
    path("orders/<int:order_id>/pre-ship/", SellerPreShipChecklistView.as_view(), name="order-pre-ship"),
    path("orders/<int:order_id>/purchase-label/", SellerPurchaseLabelView.as_view(), name="order-purchase-label"),
    path(
        "orders/<int:order_id>/tracking/admin-override/",
        TrackingAdminOverrideView.as_view(),
        name="order-tracking-admin-override",
    ),
    path("orders/tracking/webhook/", TrackingWebhookView.as_view(), name="order-tracking-webhook"),
    path("orders/", OrderListView.as_view(), name="order-list"),
    path("orders/seller/analytics/", SellerAnalyticsView.as_view(), name="seller-analytics"),
    path("orders/money/summary/", MoneySummaryView.as_view(), name="money-summary"),
    path("orders/money/cashout/", CashoutRequestView.as_view(), name="money-cashout"),
    path("orders/seller-verification/", SellerVerificationView.as_view(), name="seller-verification"),
]
