# Generated by Django 5.2.6 on 2025-10-27 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_listings', models.IntegerField(default=0)),
                ('active_listings', models.IntegerField(default=0)),
                ('sold_listings', models.IntegerField(default=0)),
                ('draft_listings', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_this_month', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_views', models.IntegerField(default=0)),
                ('total_watchers', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('listings_this_month', models.IntegerField(default=0)),
                ('sales_this_month', models.IntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Stats',
                'db_table': 'dashboard_stats',
            },
        ),
        migrations.CreateModel(
            name='PartAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=200)),
                ('vehicle_year', models.IntegerField(blank=True, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('is_multi_part', models.BooleanField(default=False, help_text='If True, analyzes all parts for the vehicle instead of single part')),
                ('time_period_days', models.IntegerField(default=90)),
                ('analysis_data', models.JSONField(default=dict)),
                ('part_number', models.CharField(blank=True, help_text='OEM or aftermarket part number', max_length=100, null=True)),
                ('category_analysis', models.JSONField(default=dict, help_text='Analysis broken down by eBay category')),
                ('filtering_stats', models.JSONField(default=dict, help_text='Vehicle matching and relevance filtering statistics')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Part Analyses',
                'db_table': 'part_analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='part_analys_user_id_96da94_idx'), models.Index(fields=['status', '-created_at'], name='part_analys_status_556820_idx')],
            },
        ),
    ]
