# Generated by Django 5.2.2 on 2026-06-02 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_listings', models.IntegerField(default=0)),
                ('active_listings', models.IntegerField(default=0)),
                ('sold_listings', models.IntegerField(default=0)),
                ('draft_listings', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_this_month', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_views', models.IntegerField(default=0)),
                ('total_watchers', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('listings_this_month', models.IntegerField(default=0)),
                ('sales_this_month', models.IntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Stats',
                'db_table': 'dashboard_stats',
            },
        ),
        migrations.CreateModel(
            name='PartAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_year', models.IntegerField(blank=True, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('is_multi_part', models.BooleanField(default=False, help_text='If True, analyzes all parts for the vehicle instead of single part')),
                ('time_period_days', models.IntegerField(default=90)),
                ('analysis_data', models.JSONField(default=dict)),
                ('part_number', models.CharField(blank=True, help_text='OEM or aftermarket part number', max_length=100, null=True)),
                ('category_analysis', models.JSONField(default=dict, help_text='Analysis broken down by eBay category')),
                ('filtering_stats', models.JSONField(default=dict, help_text='Vehicle matching and relevance filtering statistics')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('prompt_applied', models.BooleanField(default=False)),
                ('prompt_text', models.TextField(blank=True)),
                ('filtered_categories', models.JSONField(blank=True, default=list)),
                ('filtered_part_out_summary', models.JSONField(blank=True, default=dict)),
                ('filtered_categories_history', models.JSONField(blank=True, default=list)),
                ('filtered_part_out_history', models.JSONField(blank=True, default=list)),
                ('prompt_text_history', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_analyses', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_analyses', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Part Analyses',
                'db_table': 'part_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisCarPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('front_three_quarter', 'Front 3/4 view'), ('rear_three_quarter', 'Rear 3/4 view'), ('front_straight', 'Straight-on front'), ('rear_straight', 'Straight-on rear'), ('driver_side', 'Driver side profile'), ('passenger_side', 'Passenger side profile'), ('wheel_front_left', 'Wheel/Rim - Front left'), ('wheel_front_right', 'Wheel/Rim - Front right'), ('wheel_rear_left', 'Wheel/Rim - Rear left'), ('wheel_rear_right', 'Wheel/Rim - Rear right'), ('headlights', 'Headlights'), ('taillights', 'Taillights'), ('windshield', 'Windshield'), ('windows', 'All windows'), ('mirrors', 'Mirrors'), ('door_handles', 'Door handles/locks'), ('fuel_door', 'Fuel door'), ('exhaust_tips', 'Exhaust tips'), ('undercarriage', 'Undercarriage'), ('roof', 'Roof / Sunroof'), ('damage_closeups', 'Scratches/dents close-ups'), ('paint_chips_rust', 'Paint chips / rust'), ('panel_gaps', 'Panel gaps/alignment'), ('license_plate_front', 'License plate - front'), ('license_plate_rear', 'License plate - rear'), ('vin_plate', 'VIN plate'), ('dashboard_view', 'Dashboard - wide'), ('instrument_cluster', 'Instrument cluster / odometer'), ('center_console', 'Center console / infotainment'), ('steering_wheel', 'Steering wheel'), ('climate_controls', 'Climate controls'), ('gear_shifter', 'Gear shifter'), ('front_seats', 'Front seats'), ('rear_seats', 'Rear seats'), ('seat_controls', 'Seat adjustments / controls'), ('headrests', 'Headrests'), ('seatbelts', 'Seatbelts / buckles'), ('trunk', 'Trunk / cargo area'), ('under_trunk_floor', 'Under trunk floor'), ('glove_compartment', 'Glove compartment'), ('center_console_storage', 'Center console storage'), ('door_pockets', 'Door pockets'), ('overhead_storage', 'Overhead storage'), ('headliner', 'Headliner'), ('carpet_floor_mats', 'Carpet / floor mats'), ('door_panels', 'Door panels / armrests'), ('buttons_switches', 'Buttons / switches'), ('pedals', 'Pedals'), ('engine_bay_overview', 'Engine bay overview'), ('engine_block', 'Engine block / components'), ('fluid_reservoirs', 'Fluid reservoirs'), ('battery', 'Battery / terminals'), ('belts_hoses', 'Belts / hoses'), ('leaks_corrosion', 'Leaks / corrosion'), ('engine_bay_cleanliness', 'Engine bay cleanliness')], max_length=64)),
                ('image', models.ImageField(upload_to='analysis_car_photos/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_car_photos', to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_photos', to='analytics.partanalysis')),
            ],
            options={
                'db_table': 'analysis_car_photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='partanalysis',
            index=models.Index(fields=['user', '-created_at'], name='part_analys_user_id_96da94_idx'),
        ),
        migrations.AddIndex(
            model_name='partanalysis',
            index=models.Index(fields=['status', '-created_at'], name='part_analys_status_556820_idx'),
        ),
    ]
