# Generated by Django 5.2.6 on 2026-02-07 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_partanalysis_part_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCarPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('front_three_quarter', 'Front 3/4 view'), ('rear_three_quarter', 'Rear 3/4 view'), ('front_straight', 'Straight-on front'), ('rear_straight', 'Straight-on rear'), ('driver_side', 'Driver side profile'), ('passenger_side', 'Passenger side profile'), ('wheel_front_left', 'Wheel/Rim - Front left'), ('wheel_front_right', 'Wheel/Rim - Front right'), ('wheel_rear_left', 'Wheel/Rim - Rear left'), ('wheel_rear_right', 'Wheel/Rim - Rear right'), ('headlights', 'Headlights'), ('taillights', 'Taillights'), ('windshield', 'Windshield'), ('windows', 'All windows'), ('mirrors', 'Mirrors'), ('door_handles', 'Door handles/locks'), ('fuel_door', 'Fuel door'), ('exhaust_tips', 'Exhaust tips'), ('undercarriage', 'Undercarriage'), ('roof', 'Roof / Sunroof'), ('damage_closeups', 'Scratches/dents close-ups'), ('paint_chips_rust', 'Paint chips / rust'), ('panel_gaps', 'Panel gaps/alignment'), ('license_plate_front', 'License plate - front'), ('license_plate_rear', 'License plate - rear'), ('vin_plate', 'VIN plate'), ('dashboard_view', 'Dashboard - wide'), ('instrument_cluster', 'Instrument cluster / odometer'), ('center_console', 'Center console / infotainment'), ('steering_wheel', 'Steering wheel'), ('climate_controls', 'Climate controls'), ('gear_shifter', 'Gear shifter'), ('front_seats', 'Front seats'), ('rear_seats', 'Rear seats'), ('seat_controls', 'Seat adjustments / controls'), ('headrests', 'Headrests'), ('seatbelts', 'Seatbelts / buckles'), ('trunk', 'Trunk / cargo area'), ('under_trunk_floor', 'Under trunk floor'), ('glove_compartment', 'Glove compartment'), ('center_console_storage', 'Center console storage'), ('door_pockets', 'Door pockets'), ('overhead_storage', 'Overhead storage'), ('headliner', 'Headliner'), ('carpet_floor_mats', 'Carpet / floor mats'), ('door_panels', 'Door panels / armrests'), ('buttons_switches', 'Buttons / switches'), ('pedals', 'Pedals'), ('engine_bay_overview', 'Engine bay overview'), ('engine_block', 'Engine block / components'), ('fluid_reservoirs', 'Fluid reservoirs'), ('battery', 'Battery / terminals'), ('belts_hoses', 'Belts / hoses'), ('leaks_corrosion', 'Leaks / corrosion'), ('engine_bay_cleanliness', 'Engine bay cleanliness')], max_length=64)),
                ('image', models.ImageField(upload_to='analysis_car_photos/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_photos', to='analytics.partanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_car_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_car_photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
