# Generated by Django 5.2.6 on 2026-02-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_partanalysis_prompt_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='partanalysis',
            name='filtered_categories_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='partanalysis',
            name='filtered_part_out_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='partanalysis',
            name='prompt_text_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
