# Generated by Django 5.2.13 on 2026-04-13 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_partanalysis_filtered_categories_history_and_more'),
        ('vehicles', '0004_phase3_market_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='partanalysis',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_analyses', to='vehicles.vehicle'),
        ),
    ]
