# Generated by Django 5.2.2 on 2026-06-02 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('assembly', 'Assembly'), ('discount', 'Discount')], default='discount', max_length=16)),
                ('category_filters', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Bundle categories',
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disbanded', 'Disbanded')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bundle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='bundles.bundlecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='bundles.bundle')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='parts.item')),
            ],
            options={
                'unique_together': {('bundle', 'item')},
            },
        ),
    ]
