# Generated by Django 5.2.14 on 2026-06-04 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0003_bundlecategory_image'),
        ('parts', '0008_item_assembly_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for the synthetic assembly item. Required for assembly bundles.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_bundles', to='parts.category'),
        ),
    ]
