# Generated by Django 5.2.2 on 2026-06-02 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('shipping_size_default', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xl', 'XL')], default='medium', max_length=8)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='parts.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('removed', 'Removed'), ('hidden_in_assembly', 'Hidden in Assembly')], default='active', max_length=24)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('for_parts', 'For Parts')], max_length=16)),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dim_l_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dim_w_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dim_h_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shipping_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xl', 'XL')], default='medium', max_length=8)),
                ('oem_part_number', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='parts.category')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compat_level', models.CharField(choices=[('generation', 'Generation'), ('modification', 'Modification')], default='generation', max_length=16)),
                ('year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('source', models.CharField(choices=[('ai', 'AI'), ('manual', 'Manual'), ('oem_data', 'OEM Data')], default='ai', max_length=16)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_compatibilities', to='catalog.generation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='parts.item')),
                ('modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_compatibilities', to='catalog.modification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('thumbnail_url', models.CharField(blank=True, max_length=1024)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='parts.item')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('side', 'Side'), ('engine', 'Engine'), ('transmission', 'Transmission'), ('trim', 'Trim'), ('other', 'Other')], default='other', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_categories', to='parts.category')),
            ],
            options={
                'verbose_name_plural': 'Option categories',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('is_ai_eliminated', models.BooleanField(default=False)),
                ('elimination_reason', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='parts.item')),
                ('option_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='parts.optioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_snapshot', models.JSONField(blank=True, default=dict)),
                ('ai_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=8)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='parts.item')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemOptionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buyer_question', models.BooleanField(default=False)),
                ('surviving_count', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_configs', to='parts.item')),
                ('option_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_configs', to='parts.optioncategory')),
            ],
            options={
                'unique_together': {('item', 'option_category')},
            },
        ),
    ]
