# Generated by Django 5.2.14 on 2026-06-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_category_sort_order_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='item',
            new_name='parts_item_status_ebbc53_idx',
            old_name='parts_item_status_cat_price_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='parts_item_status_cb648b_idx',
            old_name='parts_item_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='itemcompatibility',
            new_name='parts_itemc_generat_01698e_idx',
            old_name='parts_ic_gen_verified_idx',
        ),
        migrations.RenameIndex(
            model_name='itemcompatibility',
            new_name='parts_itemc_item_id_1b8f20_idx',
            old_name='parts_ic_item_gen_idx',
        ),
    ]
