# Generated by Django 5.2.14 on 2026-06-03 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_rename_parts_item_status_cat_price_idx_parts_item_status_ebbc53_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='oem_part_number_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='optioncategory',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_raw', models.CharField(max_length=128)),
                ('number_normalized', models.CharField(db_index=True, max_length=128)),
                ('brand', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_part_numbers', to='parts.item')),
            ],
            options={
                'ordering': ['brand', 'number_raw'],
            },
        ),
    ]
