# Generated by Django 5.2.14 on 2026-06-03 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_partnumber_oem_normalized_required_spec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optioncategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Option categories'},
        ),
        # Clear all AI-generated option data before applying the unique constraint
        migrations.RunPython(
            lambda apps, se: apps.get_model('parts', 'Option').objects.all().delete(),
            migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('item', 'option_category')},
        ),
        migrations.AlterField(
            model_name='optioncategory',
            name='type',
            field=models.CharField(choices=[('side', 'Side'), ('position', 'Position'), ('trim', 'Trim'), ('color', 'Color'), ('other', 'Other')], default='other', max_length=16),
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('option_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_values', to='parts.optioncategory')),
            ],
            options={
                'ordering': ['sort_order', 'value'],
                'unique_together': {('option_category', 'value')},
            },
        ),
        migrations.DeleteModel(
            name='ItemOptionConfig',
        ),
        migrations.RemoveField(
            model_name='option',
            name='elimination_reason',
        ),
        migrations.RemoveField(
            model_name='option',
            name='is_ai_eliminated',
        ),
    ]
