# Generated by Django 5.2.14 on 2026-06-04 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0003_bundlecategory_image'),
        ('parts', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='assembly_bundle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_item', to='bundles.bundle'),
        ),
    ]
